name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Download repo
        uses: actions/checkout@v1

      - name: Zip froggy dir
        run: |
          cd /home/runner/work/Home-Assistant-custom-components-Froggy/Home-Assistant-custom-components-Froggy/custom_components/froggy
          zip froggy.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/Home-Assistant-custom-components-Froggy/Home-Assistant-custom-components-Froggy/custom_components/froggy/froggy.zip
          asset_name: froggy.zip
          tag: ${{ github.ref }}
          overwrite: true